### ISSUE TITLE
When are nested types needed and why?

### ISSUE THREAD

**Issue by SurajGupta** [jonsequitur/Its.Cqrs#110]
The samples use partial classes to separate nested types (e.g. CustomerAccount.Created).  I'm wondering if using nested types is a requirement for Its.CQRS to wire itself up properly to the persistence store and/or other aspects/features of Its.CQRS (i.e. must-follow convention)?  Or is that just the way the samples are coded-up?  It seems that Events and Snapshot Creators are implemented as nested types but Commands are not.  I'm trying to understand when nested types are required and why.

**Comment by jonsequitur** [comment]
Good question! This isn't made clear at all but this is just a coding convention and no part of Its.Cqrs depends on structuring code this way. The samples really evolved as part of the test-driven design process and are far from ideal as a teaching tool.

So the reasoning behind events being nested classes is that it gives them access to the aggregate's private state so they can modify it during calls to `IEvent<T>.Update`. This follows from a preference for [Tell, Don't Ask](https://pragprog.com/articles/tell-dont-ask) in aggregate design. Snapshots are nested for similar reasons. It's not required. 

As for commands, we tend not to nest them in order to avoid having people update the state of the aggregate from within the command code. Again, just a convention, and I've seen people nest the commands because they liked the way the aggregate organizes them like a sort of namespace. It's purely a matter of preference.

**Comment by SurajGupta** [comment]
Many thanks for this comprehensive answer!
