### ISSUE TITLE
Convention over configuration to convert events to in memory model

### ISSUE THREAD

**Issue by wli3** [jonsequitur/Its.Cqrs#200]
So _Update_ method in the _Event_ can be shrunk down a lot.

For example, if there is event _UserAddressChanged_
_{"NewAddress": "650 S R.L. Thornton Fwy, Dallas"}_

the _Update_ method in UserAddressChange would look like this
_bankAccount.Address = @event.NewAddress;_

Actually this kind of _override or add_ is majority of the _Update_ logic. This behavior should be the default without extra code. Say, if the field is started with _New_, then override or add corresponding field of in memory object. 

This sounds hacky in the beginning, however, Event should be align with .Domain logic, so in this case, highly couple is encouraged. In extreme case, _Update_ would be completely redundant, if your event modeling is perfect. However, a basic override convention is a good enough at this point.

BankAccountCreated --- new BankAccount(); Created is the convention of create new object, and the string before Created is the class name
SavingDeposited { "AddSaving": 30} --- bankAccount.Saving += 30; Add is the method of how to update, Saving is the field name

**Comment by jonsequitur** [comment]
This kind of convention is likely only partly applicable in any given domain model, allowing some fields to be set by convention and others still needing to be updated "manually".

For example, this would work for a known set of verbs, typically CRUD-y verbs such as Updated, Changed, Created, Deleted. Ideally though you want your domain language to be more specific than that. Instead of `UserAddressChanged`, I look for event names that capture why the address changed. Did the user move? Was additional information added to the address by customer service after a failed delivery attempt?  

So this kind of convention is deliberately left out of scope because it's going to vary widely with how people model different domains.
